DROP TABLE IF EXISTS "BlacklistPair";

CREATE TABLE "BlacklistedPlayer" (
  "id" SERIAL PRIMARY KEY,
  "playerId" INT NOT NULL UNIQUE REFERENCES "Player" ("id") ON DELETE CASCADE,
  "createdAt" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
